[package]
name = "helia-ipns"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "IPNS (InterPlanetary Name System) implementation for Helia"

[dependencies]
helia-interface = { version = "0.1.0", path = "../helia-interface" }

# Core async runtime
async-trait.workspace = true
futures.workspace = true
tokio.workspace = true

# Error handling
thiserror.workspace = true

# IPFS and multiformats
cid.workspace = true
multihash.workspace = true

# Utilities
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
rust-helia = { version = "0.1.2", path = "../rust-helia" }
